// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaOY9fql4hf5vmmFGSqeWPDnicz6nTNGY',
    appId: '1:858173166018:web:e3ced1d4e87c2dba92865b',
    messagingSenderId: '858173166018',
    projectId: 'focus-tracker-9d665',
    authDomain: 'focus-tracker-9d665.firebaseapp.com',
    storageBucket: 'focus-tracker-9d665.firebasestorage.app',
    measurementId: 'G-21PS1713B9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZs3uLWrK0kgYMq26uz4bBWzm6LI7ZFvc',
    appId: '1:858173166018:android:8be4ac97e96995a692865b',
    messagingSenderId: '858173166018',
    projectId: 'focus-tracker-9d665',
    storageBucket: 'focus-tracker-9d665.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBx0JT0qSM99GTk0MDStEmZZWHpnf6bFs',
    appId: '1:858173166018:ios:79eafbf9b34802c492865b',
    messagingSenderId: '858173166018',
    projectId: 'focus-tracker-9d665',
    storageBucket: 'focus-tracker-9d665.firebasestorage.app',
    iosBundleId: 'com.example.focusTrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBx0JT0qSM99GTk0MDStEmZZWHpnf6bFs',
    appId: '1:858173166018:ios:79eafbf9b34802c492865b',
    messagingSenderId: '858173166018',
    projectId: 'focus-tracker-9d665',
    storageBucket: 'focus-tracker-9d665.firebasestorage.app',
    iosBundleId: 'com.example.focusTrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDaOY9fql4hf5vmmFGSqeWPDnicz6nTNGY',
    appId: '1:858173166018:web:764ff5a49127157e92865b',
    messagingSenderId: '858173166018',
    projectId: 'focus-tracker-9d665',
    authDomain: 'focus-tracker-9d665.firebaseapp.com',
    storageBucket: 'focus-tracker-9d665.firebasestorage.app',
    measurementId: 'G-ERPCBM1RE4',
  );
}
